apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"appmesh.k8s.aws/v1beta2","kind":"VirtualRouter","metadata":{"annotations":{},"name":"httpbin-router","namespace":"default"},"spec":{"listeners":[{"portMapping":{"port":8000,"protocol":"http"}}],"routes":[{"httpRoute":{"action":{"weightedTargets":[{"virtualNodeRef":{"name":"httpbin"},"weight":100}]},"match":{"prefix":"/"}},"name":"httpRoute"}]}}
  creationTimestamp: "2020-11-19T04:10:41Z"
  finalizers:
  - finalizers.appmesh.k8s.aws/aws-appmesh-resources
  generation: 1
  managedFields:
  - apiVersion: appmesh.k8s.aws/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:listeners: {}
        f:routes: {}
    manager: kubectl
    operation: Update
    time: "2020-11-19T04:10:41Z"
  - apiVersion: appmesh.k8s.aws/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"finalizers.appmesh.k8s.aws/aws-appmesh-resources": {}
      f:status:
        .: {}
        f:conditions: {}
        f:observedGeneration: {}
        f:routeARNs:
          .: {}
          f:httpRoute: {}
        f:virtualRouterARN: {}
    manager: controller
    operation: Update
    time: "2020-11-19T04:15:00Z"
  name: httpbin-router
  namespace: default
  resourceVersion: "7013699"
  selfLink: /apis/appmesh.k8s.aws/v1beta2/namespaces/default/virtualrouters/httpbin-router
  uid: ac81b9ff-34eb-4d01-9605-c00148726c59
spec:
  awsName: httpbin-router_default
  listeners:
  - portMapping:
      port: 8000
      protocol: http
  meshRef:
    name: mymesh
    uid: 40f9c639-8a5c-42c8-8772-bc51b213271d
  routes:
  - httpRoute:
      action:
        weightedTargets:
        - virtualNodeRef:
            name: httpbin
          weight: 100
      match:
        prefix: /
    name: httpRoute
status:
  conditions:
  - lastTransitionTime: "2020-11-19T04:15:00Z"
    status: "True"
    type: VirtualRouterActive
  observedGeneration: 1
  routeARNs:
    httpRoute: arn:aws:appmesh:ap-northeast-1:054818973631:mesh/mymesh/virtualRouter/httpbin-router_default/route/httpRoute
  virtualRouterARN: arn:aws:appmesh:ap-northeast-1:054818973631:mesh/mymesh/virtualRouter/httpbin-router_default
