apiVersion: v1
kind: ServiceAccount
metadata:
  name: goclient
---
apiVersion: v1
kind: Service
metadata:
  name: goclient
  labels:
    app: goclient
spec:
  type: NodePort
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    app: goclient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goclient
      version: v1
  template:
    metadata:
      labels:
        app: goclient
        version: v1
    spec:
      serviceAccountName: goclient
      containers:
      - image: docker.io/malphi/goclient:v5
        imagePullPolicy: IfNotPresent
        name: goclient
        ports:
        - containerPort: 8888
